# Generated by Django 4.1.7 on 2023-03-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='music',
        ),
    ]
